"use client";

import { useState } from "react";
import { Download, FileText, Loader2 } from "lucide-react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Button } from "@indihub/ui";
import { saveDownload } from "@/lib/admin-finance-api";
import { formatMoney } from "@/lib/storefront-api";
import { downloadSellerStatement, listSellerStatements } from "@/lib/seller-finance-api";
import {
  SellerAuthNotice,
  SellerEmptyState,
  SellerErrorPanel,
  SellerMetric,
  SellerOnboardingRequired,
  SellerPagination,
  SellerPanel,
  SellerSkeleton,
  SellerStatusPill,
  formatDateTime,
  isSellerOnboardingRequiredError,
  useSellerAuth
} from "../seller-ui";

export function SellerStatementsClient() {
  const sellerAuth = useSellerAuth();
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const statementsQuery = useQuery({
    queryKey: ["seller-finance-statements", sellerAuth.authKey, page, pageSize],
    queryFn: () => listSellerStatements(sellerAuth.authHeaders, { page, limit: pageSize }),
    enabled: sellerAuth.enabled,
    retry: false
  });
  const download = useMutation({
    mutationFn: ({ statementId, format }: { statementId: string; format: "csv" | "pdf" }) => downloadSellerStatement(sellerAuth.authHeaders, statementId, format),
    onSuccess: saveDownload
  });

  if (!sellerAuth.enabled) {
    return <SellerAuthNotice />;
  }

  if (statementsQuery.isLoading) {
    return <SellerSkeleton />;
  }

  if (statementsQuery.error) {
    if (isSellerOnboardingRequiredError(statementsQuery.error)) {
      return <SellerOnboardingRequired message="Complete seller onboarding before viewing statements." />;
    }

    return <SellerErrorPanel error={statementsQuery.error} onRetry={() => void statementsQuery.refetch()} />;
  }

  const statements = statementsQuery.data?.items ?? [];
  // Keep currencies separate because combining them would produce a misleading total.
  const summary = statementsQuery.data?.summary;
  const totalNetLabel = summary?.totalsByCurrency.length
    ? summary.totalsByCurrency
        .map(({ currency, netPayablePaise }) => formatMoney(netPayablePaise, currency))
        .join(" + ")
    : formatMoney(0);

  return (
    <div className="grid gap-5">
      <div className="grid gap-4 md:grid-cols-3">
        <SellerMetric label="Statements" value={summary?.statementCount ?? statementsQuery.data?.total ?? 0} note="Generated by admin" />
        <SellerMetric label="Statement value" value={totalNetLabel} note="Net payable total" />
        <SellerMetric label="Downloads" value="CSV + PDF" note="Available per statement" />
      </div>
      {download.error ? <SellerErrorPanel error={download.error} /> : null}
      <div className="grid gap-3">
        {statements.map((statement) => {
          const activeDownload = download.isPending && download.variables?.statementId === statement.id
            ? download.variables.format
            : null;
          return <SellerPanel key={statement.id}>
            <div className="grid gap-3 md:grid-cols-[1fr_auto] md:items-center">
              <div className="flex items-start gap-3">
                <span className="grid h-10 w-10 place-items-center rounded-md bg-[#EAF1F7] text-[#163B5C]">
                  <FileText className="h-5 w-5" aria-hidden="true" />
                </span>
                <div>
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="font-black text-[#1F2933]">{statement.statementNumber}</p>
                    <SellerStatusPill status={statement.status} />
                  </div>
                  <p className="mt-1 text-sm font-semibold text-[#667085]">{formatDateTime(statement.generatedAt)}</p>
                </div>
              </div>
              <div className="flex flex-wrap gap-2 md:justify-end">
                <span className="mr-2 self-center text-lg font-black text-[#163B5C]">{formatMoney(statement.netPayablePaise, statement.currency)}</span>
                <Button type="button" variant="outline" size="sm" disabled={download.isPending} onClick={() => download.mutate({ statementId: statement.id, format: "csv" })}>
                  {activeDownload === "csv" ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" /> : <Download className="h-4 w-4" aria-hidden="true" />}
                  {activeDownload === "csv" ? "Preparing CSV" : "CSV"}
                </Button>
                <Button type="button" size="sm" disabled={download.isPending} onClick={() => download.mutate({ statementId: statement.id, format: "pdf" })}>
                  {activeDownload === "pdf" ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" /> : <Download className="h-4 w-4" aria-hidden="true" />}
                  {activeDownload === "pdf" ? "Preparing PDF" : "PDF"}
                </Button>
              </div>
            </div>
          </SellerPanel>;
        })}
      </div>
      {statements.length === 0 ? <SellerEmptyState title="No statements yet" message="Statements appear after admin generates them from approved or paid payouts." /> : null}
      {(statementsQuery.data?.total ?? 0) > 0 ? (
        <SellerPagination
          page={page}
          pageSize={pageSize}
          total={statementsQuery.data?.total ?? 0}
          isLoading={statementsQuery.isFetching}
          onPageChange={setPage}
          onPageSizeChange={(value) => {
            setPage(1);
            setPageSize(value);
          }}
          itemLabel="statements"
        />
      ) : null}
    </div>
  );
}
