import { EmailRecipientType, EmailTemplateCategory } from "@indihub/database";

export type EmailTriggerCatalogItem = {
  eventCode: string;
  eventName: string;
  category: EmailTemplateCategory;
  recipientType: EmailRecipientType;
  defaultTemplateCode: string;
  variableKeys: string[];
};

export const EMAIL_TRIGGER_EVENTS = {
  CUSTOMER_REGISTERED: "CUSTOMER_REGISTERED",
  SELLER_REGISTRATION_SUBMITTED_SELLER: "SELLER_REGISTRATION_SUBMITTED_SELLER",
  SELLER_REGISTRATION_SUBMITTED_ADMIN: "SELLER_REGISTRATION_SUBMITTED_ADMIN",
  SELLER_APPROVED: "SELLER_APPROVED",
  SELLER_REJECTED: "SELLER_REJECTED",
  PRODUCT_SUBMITTED_SELLER: "PRODUCT_SUBMITTED_SELLER",
  PRODUCT_SUBMITTED_ADMIN: "PRODUCT_SUBMITTED_ADMIN",
  PRODUCT_APPROVED: "PRODUCT_APPROVED",
  PRODUCT_REJECTED: "PRODUCT_REJECTED",
  ORDER_PLACED_CUSTOMER: "ORDER_PLACED_CUSTOMER",
  ORDER_RECEIVED_SELLER: "ORDER_RECEIVED_SELLER",
  ORDER_PLACED_ADMIN: "ORDER_PLACED_ADMIN",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_PROCESSING: "ORDER_PROCESSING",
  ORDER_DISPATCHED: "ORDER_DISPATCHED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  DELIVERY_ASSIGNED_PARTNER: "DELIVERY_ASSIGNED_PARTNER",
  DELIVERY_ASSIGNMENT_ACCEPTED_ADMIN: "DELIVERY_ASSIGNMENT_ACCEPTED_ADMIN",
  DELIVERY_ASSIGNMENT_REJECTED_ADMIN: "DELIVERY_ASSIGNMENT_REJECTED_ADMIN",
  DELIVERY_COD_COLLECTED_ADMIN: "DELIVERY_COD_COLLECTED_ADMIN",
  DELIVERY_ROUTING_FAILED_ADMIN: "DELIVERY_ROUTING_FAILED_ADMIN",
  MANUAL_TRANSPORT_REQUIRED_ADMIN: "MANUAL_TRANSPORT_REQUIRED_ADMIN",
  MANUAL_TRANSPORT_REQUIRED_SELLER: "MANUAL_TRANSPORT_REQUIRED_SELLER",
  B2B_ENQUIRY_SUBMITTED_BUYER: "B2B_ENQUIRY_SUBMITTED_BUYER",
  B2B_ENQUIRY_SUBMITTED_SELLER: "B2B_ENQUIRY_SUBMITTED_SELLER",
  B2B_ENQUIRY_SUBMITTED_ADMIN: "B2B_ENQUIRY_SUBMITTED_ADMIN",
  B2B_ENQUIRY_RESPONSE_BUYER: "B2B_ENQUIRY_RESPONSE_BUYER",
  SUPPORT_REQUEST_RECEIVED: "SUPPORT_REQUEST_RECEIVED",
  SUPPORT_REQUEST_ADMIN_ALERT: "SUPPORT_REQUEST_ADMIN_ALERT",
  SUPPORT_REQUEST_RESPONDED: "SUPPORT_REQUEST_RESPONDED",
} as const;

export const emailTriggerCatalog: EmailTriggerCatalogItem[] = [
  {
    eventCode: EMAIL_TRIGGER_EVENTS.CUSTOMER_REGISTERED,
    eventName: "Customer account created",
    category: EmailTemplateCategory.CUSTOMER,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "CUSTOMER_ACCOUNT_CREATED",
    variableKeys: ["customerName"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.SELLER_REGISTRATION_SUBMITTED_SELLER,
    eventName: "Seller registration received",
    category: EmailTemplateCategory.SELLER,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "SELLER_REGISTRATION_RECEIVED",
    variableKeys: ["sellerName", "contactName"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.SELLER_REGISTRATION_SUBMITTED_ADMIN,
    eventName: "Seller registration admin alert",
    category: EmailTemplateCategory.SELLER,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "SELLER_REGISTRATION_RECEIVED",
    variableKeys: ["sellerName", "sellerType", "contactEmail"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.SELLER_APPROVED,
    eventName: "Seller approved",
    category: EmailTemplateCategory.SELLER,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "SELLER_APPROVED",
    variableKeys: ["sellerName", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.SELLER_REJECTED,
    eventName: "Seller rejected or suspended",
    category: EmailTemplateCategory.SELLER,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "SELLER_REJECTED",
    variableKeys: ["sellerName", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.PRODUCT_SUBMITTED_SELLER,
    eventName: "Product submitted seller receipt",
    category: EmailTemplateCategory.PRODUCT,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "PRODUCT_SUBMITTED",
    variableKeys: ["productName", "sellerName"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.PRODUCT_SUBMITTED_ADMIN,
    eventName: "Product submitted admin alert",
    category: EmailTemplateCategory.PRODUCT,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "PRODUCT_SUBMITTED",
    variableKeys: ["productName", "sellerName"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.PRODUCT_APPROVED,
    eventName: "Product approved",
    category: EmailTemplateCategory.PRODUCT,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "PRODUCT_APPROVED",
    variableKeys: ["productName", "sellerName", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.PRODUCT_REJECTED,
    eventName: "Product rejected",
    category: EmailTemplateCategory.PRODUCT,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "PRODUCT_REJECTED",
    variableKeys: ["productName", "sellerName", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.ORDER_PLACED_CUSTOMER,
    eventName: "Order placed customer receipt",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "ORDER_PLACED_CUSTOMER",
    variableKeys: ["orderNumber", "totalPaise"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.ORDER_RECEIVED_SELLER,
    eventName: "Order received by seller",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "ORDER_RECEIVED_SELLER",
    variableKeys: ["orderNumber", "totalPaise"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.ORDER_PLACED_ADMIN,
    eventName: "New order admin alert",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "ORDER_ALERT_ADMIN",
    variableKeys: ["orderNumber", "totalPaise"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.ORDER_CONFIRMED,
    eventName: "Order confirmed",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "ORDER_CONFIRMED",
    variableKeys: ["orderNumber", "orderStatus", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.ORDER_PROCESSING,
    eventName: "Order processing",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "ORDER_PROCESSING",
    variableKeys: ["orderNumber", "orderStatus", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.ORDER_DISPATCHED,
    eventName: "Order dispatched or in transit",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "ORDER_DISPATCHED",
    variableKeys: ["orderNumber", "orderStatus", "deliveryStatus", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.ORDER_DELIVERED,
    eventName: "Order delivered",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "ORDER_DELIVERED",
    variableKeys: ["orderNumber", "orderStatus", "deliveryStatus", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.ORDER_CANCELLED,
    eventName: "Order cancelled",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "ORDER_CANCELLED",
    variableKeys: ["orderNumber", "orderStatus", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.PAYMENT_PENDING,
    eventName: "Payment pending",
    category: EmailTemplateCategory.PAYMENT,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "PAYMENT_PENDING",
    variableKeys: ["orderNumber", "paymentStatus", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.PAYMENT_SUCCESS,
    eventName: "Payment successful",
    category: EmailTemplateCategory.PAYMENT,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "PAYMENT_SUCCESS",
    variableKeys: ["orderNumber", "paymentStatus", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.PAYMENT_FAILED,
    eventName: "Payment failed",
    category: EmailTemplateCategory.PAYMENT,
    recipientType: EmailRecipientType.CUSTOMER,
    defaultTemplateCode: "PAYMENT_FAILED",
    variableKeys: ["orderNumber", "paymentStatus", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.DELIVERY_ASSIGNED_PARTNER,
    eventName: "Order assigned to delivery partner",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.DELIVERY_PARTNER,
    defaultTemplateCode: "DELIVERY_ASSIGNED_PARTNER",
    variableKeys: ["orderNumber", "partnerName", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.DELIVERY_ASSIGNMENT_ACCEPTED_ADMIN,
    eventName: "Delivery partner accepted assignment",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "DELIVERY_ASSIGNMENT_ACCEPTED_ADMIN",
    variableKeys: ["orderNumber", "partnerName", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.DELIVERY_ASSIGNMENT_REJECTED_ADMIN,
    eventName: "Delivery partner rejected assignment",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "DELIVERY_ASSIGNMENT_REJECTED_ADMIN",
    variableKeys: ["orderNumber", "partnerName", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.DELIVERY_COD_COLLECTED_ADMIN,
    eventName: "Delivery COD collected admin alert",
    category: EmailTemplateCategory.PAYMENT,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "DELIVERY_COD_COLLECTED_ADMIN",
    variableKeys: ["orderNumber", "collectedAmountPaise", "partnerName"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.DELIVERY_ROUTING_FAILED_ADMIN,
    eventName: "Delivery routing failed admin alert",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "ORDER_ALERT_ADMIN",
    variableKeys: ["orderNumber", "shipmentNumber", "sellerName", "deliveryMode", "note"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.MANUAL_TRANSPORT_REQUIRED_ADMIN,
    eventName: "Manual transport required admin alert",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "ORDER_ALERT_ADMIN",
    variableKeys: [
      "orderNumber",
      "shipmentNumber",
      "sellerName",
      "packageDimensions",
      "buyerDestination",
      "sellerContact",
      "note",
    ],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.MANUAL_TRANSPORT_REQUIRED_SELLER,
    eventName: "Manual transport required seller alert",
    category: EmailTemplateCategory.ORDER,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "ORDER_RECEIVED_SELLER",
    variableKeys: [
      "orderNumber",
      "shipmentNumber",
      "sellerName",
      "packageDimensions",
      "buyerDestination",
      "sellerContact",
      "note",
    ],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.B2B_ENQUIRY_SUBMITTED_BUYER,
    eventName: "B2B enquiry submitted buyer receipt",
    category: EmailTemplateCategory.B2B,
    recipientType: EmailRecipientType.BUSINESS_BUYER,
    defaultTemplateCode: "B2B_ENQUIRY_SUBMITTED",
    variableKeys: ["companyName", "enquiryId", "quantity"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.B2B_ENQUIRY_SUBMITTED_SELLER,
    eventName: "B2B enquiry seller alert",
    category: EmailTemplateCategory.B2B,
    recipientType: EmailRecipientType.SELLER,
    defaultTemplateCode: "B2B_ENQUIRY_ALERT",
    variableKeys: ["companyName", "sellerName", "enquiryId", "quantity"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.B2B_ENQUIRY_SUBMITTED_ADMIN,
    eventName: "B2B enquiry admin alert",
    category: EmailTemplateCategory.B2B,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "B2B_ENQUIRY_ALERT",
    variableKeys: ["companyName", "enquiryId", "quantity"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.B2B_ENQUIRY_RESPONSE_BUYER,
    eventName: "B2B enquiry response",
    category: EmailTemplateCategory.B2B,
    recipientType: EmailRecipientType.BUSINESS_BUYER,
    defaultTemplateCode: "B2B_ENQUIRY_RESPONSE",
    variableKeys: ["companyName", "enquiryId", "responseSource", "quotedPricePaise"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.SUPPORT_REQUEST_RECEIVED,
    eventName: "Support request received",
    category: EmailTemplateCategory.SUPPORT,
    recipientType: EmailRecipientType.SUPPORT_REQUESTER,
    defaultTemplateCode: "SUPPORT_REQUEST_RECEIVED",
    variableKeys: ["name", "subject", "requestId", "topic", "orderNumber"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.SUPPORT_REQUEST_ADMIN_ALERT,
    eventName: "Support request admin alert",
    category: EmailTemplateCategory.SUPPORT,
    recipientType: EmailRecipientType.ADMIN,
    defaultTemplateCode: "SUPPORT_REQUEST_ALERT",
    variableKeys: ["name", "email", "subject", "requestId", "topic", "requesterType", "orderNumber"],
  },
  {
    eventCode: EMAIL_TRIGGER_EVENTS.SUPPORT_REQUEST_RESPONDED,
    eventName: "Support request response",
    category: EmailTemplateCategory.SUPPORT,
    recipientType: EmailRecipientType.SUPPORT_REQUESTER,
    defaultTemplateCode: "SUPPORT_REQUEST_RESPONDED",
    variableKeys: ["name", "subject", "requestId", "responseMessage"],
  },
];

export function findEmailTriggerCatalogItem(eventCode: string, recipientType: EmailRecipientType) {
  return emailTriggerCatalog.find(
    (item) => item.eventCode === eventCode && item.recipientType === recipientType,
  );
}
