ALTER TYPE "SellerLedgerEntryType" ADD VALUE IF NOT EXISTS 'SERVICE_RECEIVABLE_OPENED';
ALTER TYPE "SellerLedgerEntryType" ADD VALUE IF NOT EXISTS 'SERVICE_RECEIVABLE_SETTLED';
ALTER TYPE "SellerLedgerEntryType" ADD VALUE IF NOT EXISTS 'SERVICE_RECEIVABLE_WAIVED';
ALTER TYPE "SellerLedgerEntryType" ADD VALUE IF NOT EXISTS 'SERVICE_RECEIVABLE_REVERSED';
ALTER TYPE "SellerLedgerEntryType" ADD VALUE IF NOT EXISTS 'SERVICE_RECEIVABLE_OFFSET';
