export type ReturnsCopy = typeof enInReturnsCopy;

export const enInReturnsCopy = {
  accountEntryText: "Track return requests and refunds",
  accountEntryTitle: "Returns & refunds",
  addressHelp: "Pickup uses your original delivery address. Contact support if this address is wrong.",
  alreadySubmittedGuard: "We are checking the latest return status before another submit.",
  caughtUp: "You are all caught up.",
  createTitle: "Request return",
  createDescription: "Select the products you want to return. Backend checks final quantity, payment, delivery, and policy rules before accepting.",
  disabledMessage: "Returns are currently unavailable in the app. Please contact support for this order.",
  disabledTitle: "Returns unavailable",
  detailLoadErrorTitle: "Return could not load",
  detailLoading: "Loading return...",
  detailSignInMessage: "Return details are linked to your 1HandIndia account.",
  detailSignInTitle: "Sign in to view return",
  detailsAction: "View details",
  deliveryAddressFallback: "Delivery address",
  deliveredLabel: "delivered",
  emptyListAction: "View orders",
  emptyListMessage: "Return requests you create will appear here with pickup and refund updates.",
  emptyListTitle: "No return requests yet",
  fallbackReturnItem: "Return item",
  formReasonLabel: "Return reason",
  formReasonPlaceholder: "Example: Product arrived damaged",
  formSubmit: "Submit return request",
  formSubmitting: "Submitting return...",
  genericRetryMessage: "Check your connection and retry.",
  createSignInTitle: "Sign in to request return",
  decreaseQuantityHint: "Decrease return quantity",
  eachLabel: "each",
  increaseQuantityHint: "Increase return quantity",
  itemSelectHint: "Double tap to select or remove this item from the return request.",
  listLoadMore: "Load more returns",
  listLoadErrorTitle: "Returns could not load",
  listLoadingMore: "Loading more...",
  listPreparing: "Preparing returns...",
  listSignInMessage: "Return requests are linked to your 1HandIndia account.",
  listSignInTitle: "Sign in to view returns",
  listTitle: "Returns & refunds",
  modeLabel: "Mode",
  networkError: "Connection is unstable. Your form is saved here, so you can retry.",
  notAssigned: "Not assigned",
  noteLabel: "More details",
  noteSafeLabel: "Details",
  notePlaceholder: "Optional details for the support team",
  orderLoadErrorTitle: "Order could not load",
  orderMissingMessage: "Open this screen from your order detail.",
  orderMissingTitle: "Order not found",
  orderUnavailableMessage: "This order is not available for this account.",
  pickupAddressTitle: "Pickup address",
  pickupAddressUnavailable: "Pickup address is not available for this return.",
  pickupShipmentTitle: "Pickup and shipment",
  preparingForm: "Preparing return form...",
  quantityControlsLabel: "Return quantity controls",
  quantityShort: "Qty",
  quantityHint: "Adjust quantity for this return item.",
  rateLimited: "Too many attempts. Please wait a minute and try again.",
  reasonSafeLabel: "Reason",
  replacement: "Replacement",
  refund: "Refund",
  refreshBeforeRetry: "Refresh before retry",
  retry: "Retry",
  resolutionLabel: "Preferred resolution",
  resolutionSafeLabel: "Resolution",
  returnCta: "Start return",
  returnEligibleTitle: "Return available",
  returnLockedTitle: "Return locked",
  returnLockedMessage: "Returns are available only after delivery and after payment is completed or not required.",
  returnModeLabel: "Return pickup method",
  returnModePickup: "Platform pickup",
  returnModeSelfShip: "Self ship",
  returnNotFoundMessage: "Open the request from your returns list.",
  returnNotFoundTitle: "Return not found",
  returnOrderHelp: "Select delivered items, choose refund or replacement, and track pickup from your account.",
  returnRequestTitle: "Return request",
  returnSubmitFallbackError: "Return request could not be submitted.",
  returnUnavailableMessage: "This return request is not available for your account.",
  selectedItemsLabel: "Selected items",
  sessionExpired: "Your session expired. Sign in again, then retry this saved return form.",
  timelineTitle: "Return timeline",
  trackingLabel: "Tracking",
  courierLabel: "Courier",
  unavailableQuantity: "No return quantity available",
  updatedLabel: "Updated",
  viewOrder: "View order",
  validationNoItems: "Select at least one item to return.",
  validationReason: "Enter a return reason.",
  validationReasonLength: "Return reason must be 160 characters or less.",
  validationNoteLength: "Details must be 1000 characters or less.",
};

export function returnsCopy(_locale?: string | null): ReturnsCopy {
  return enInReturnsCopy;
}
