import type { OrderTaxRegisterRow } from "./order-tax-register.service";

export function orderTaxRegisterCsv(rows: OrderTaxRegisterRow[]) {
  return csv([
    [
      "Source",
      "Channel",
      "Transaction",
      "Parent Order",
      "Seller Scope",
      "Transaction Date",
      "Invoice Number",
      "Invoice Type",
      "Invoice Status",
      "Invoice Date",
      "Financial Year",
      "Original Invoice",
      "Seller",
      "Seller GSTIN",
      "Buyer",
      "Buyer GSTIN",
      "Buyer GST Registration",
      "Place of Supply State Code",
      "Place of Supply State",
      "Supply Type",
      "HSN/SAC",
      "Description",
      "Classification",
      "Quantity",
      "UQC",
      "GST Rate %",
      "Taxable Value (INR)",
      "CGST (INR)",
      "SGST (INR)",
      "IGST (INR)",
      "Cess (INR)",
      "Total GST (INR)",
      "Line Value (INR)",
      "Invoice Value (INR, repeated per document line)",
      "Payment ID",
      "Payment Provider",
      "Payment Status",
      "Payment Date",
      "Paid Amount (INR)",
      "Settlement ID",
      "Settlement Status",
      "Payout ID",
      "Readiness",
      "Reconciliation",
      "Warnings",
      "Value Source",
      "Source Record Type",
      "Source Record ID",
      "Reverse Charge",
      "GSTR Section",
      "IRN",
      "IRN Acknowledgement",
      "IRN Acknowledgement Date",
      "E-way Bill",
      "E-way Bill Date",
      "E-way Bill Valid Until",
      "Document Created",
      "Document Issued",
      "Document Cancelled",
      "Cancellation Reason",
      "Exported At",
    ],
    ...rows.map((row) => [
      row.source,
      row.channel,
      row.transactionNumber,
      row.parentOrderNumber ?? "",
      row.sellerScopeId ?? "",
      date(row.transactionDate),
      row.documentNumber ?? "",
      row.documentType ?? "",
      row.documentStatus ?? "",
      date(row.documentDate),
      row.financialYear ?? "",
      row.originalDocumentNumber ?? "",
      row.sellerName,
      row.sellerGstin ?? "",
      row.buyerName,
      row.buyerGstin ?? "",
      row.buyerTaxRegistrationStatus,
      row.placeOfSupplyStateCode ?? "",
      row.placeOfSupplyState ?? "",
      row.supplyType ?? "",
      row.hsnSacCode ?? "",
      row.description,
      row.taxClassification,
      row.quantity,
      row.uqc,
      row.gstRatePercent,
      rupees(row.taxableValuePaise),
      rupees(row.cgstPaise),
      rupees(row.sgstPaise),
      rupees(row.igstPaise),
      rupees(row.cessPaise),
      rupees(row.totalTaxPaise),
      rupees(row.lineValuePaise),
      rupees(row.invoiceValuePaise),
      row.paymentId ?? "",
      row.paymentProvider ?? "",
      row.paymentStatus ?? "",
      date(row.paymentDate),
      rupees(row.paidAmountPaise),
      row.settlementId ?? "",
      row.settlementStatus ?? "",
      row.payoutId ?? "",
      row.readinessStatus,
      row.reconciliationStatus,
      row.warningCodes.join("|"),
      row.valueSource,
      row.sourceRecordType ?? "",
      row.sourceRecordId ?? "",
      row.reverseCharge ? "Yes" : "No",
      row.gstrSupplySection ?? "",
      row.irn ?? "",
      row.acknowledgementNumber ?? "",
      date(row.acknowledgementDate),
      row.eWayBillNumber ?? "",
      date(row.eWayBillDate),
      date(row.eWayBillValidUntil),
      date(row.documentCreatedAt),
      date(row.documentDate),
      date(row.documentCancelledAt),
      row.documentCancellationReason ?? "",
      new Date().toISOString(),
    ]),
  ]);
}

function csv(rows: Array<Array<string | number>>) {
  return rows.map((row) => row.map(cell).join(",")).join("\n");
}

function cell(value: string | number) {
  const text = String(value ?? "");
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, "\"\"")}"` : text;
}

function date(value?: Date | string | null) {
  if (!value) return "";
  const parsed = value instanceof Date ? value : new Date(value);
  return Number.isNaN(parsed.getTime()) ? "" : parsed.toISOString();
}

function rupees(paise: number) {
  return (paise / 100).toFixed(2);
}
