export const adminNav = [
  { group: "Overview", label: "Dashboard", href: "/admin" },
  { group: "People", label: "Customers", href: "/admin/customers" },
  { group: "People", label: "Users & roles", href: "/admin/users" },
  { group: "People", label: "Sellers", href: "/admin/sellers" },
  { group: "People", label: "Seller approvals", href: "/admin/sellers/approvals" },
  { group: "People", label: "Business buyers", href: "/admin/business-buyers" },
  { group: "Commerce", label: "Products", href: "/admin/products" },
  { group: "Commerce", label: "Product approvals", href: "/admin/products/approvals" },
  { group: "Commerce", label: "Orders", href: "/admin/orders" },
  { group: "Commerce", label: "B2B enquiries", href: "/admin/b2b-enquiries" },
  { group: "Commerce", label: "Support", href: "/admin/support" },
  { group: "Content", label: "Content management", href: "/admin/cms" },
  { group: "Content", label: "Categories", href: "/admin/categories" },
  { group: "Content", label: "Locations", href: "/admin/locations" },
  { group: "Content", label: "Location import", href: "/admin/locations/import" },
  { group: "Operations", label: "Location serviceability", href: "/admin/locations/serviceability" },
  { group: "Operations", label: "Reports", href: "/admin/reports" },
  { group: "Operations", label: "Delivery operations", href: "/admin/delivery" },
  { group: "Operations", label: "Courier workspace", href: "/courier" },
  { group: "Finance", label: "Seller subscriptions", href: "/admin/seller-subscriptions" },
  { group: "Finance", label: "Finance workspace", href: "/finance" },
  { group: "Finance", label: "Commission rules", href: "/admin/finance/commission-rules" },
  { group: "Finance", label: "Settlements", href: "/admin/finance/settlements" },
  { group: "Finance", label: "Payouts", href: "/admin/finance/payouts" },
  { group: "Finance", label: "Seller ledger", href: "/admin/finance/ledger" },
  { group: "Finance", label: "Statements", href: "/admin/finance/statements" },
  { group: "Operations", label: "Email", href: "/admin/email" },
  { group: "Operations", label: "Payments", href: "/admin/payments" },
  { group: "Operations", label: "Storage", href: "/admin/storage" },
  { group: "Operations", label: "Audit logs", href: "/admin/audit-logs" },
  { group: "Operations", label: "Settings", href: "/admin/settings/general" },
];

export const financeNav = [
  { group: "Overview", label: "Dashboard", href: "/finance" },
  { group: "Collections", label: "COD collections", href: "/finance/cod-collections" },
  { group: "Collections", label: "Bank transfers", href: "/finance/bank-transfers" },
  { group: "Collections", label: "Payment status", href: "/finance/payment-status" },
  { group: "Seller finance", label: "Settlements", href: "/finance/settlements" },
  { group: "Seller finance", label: "Payouts", href: "/finance/payouts" },
  { group: "Seller finance", label: "Ledger", href: "/finance/ledger" },
  { group: "Seller finance", label: "Statements", href: "/finance/statements" },
  { group: "Rules", label: "Commission rules", href: "/finance/commission-rules" },
  { group: "Reports", label: "Payment reports", href: "/finance/reports" },
  { group: "Settings", label: "Payment settings", href: "/finance/settings" },
];

export const courierNav = [
  { group: "Overview", label: "Dashboard", href: "/courier" },
  { group: "Packages", label: "Packages", href: "/courier/packages" },
  { group: "Packages", label: "Routing failures", href: "/courier/routing-failures" },
  { group: "Local delivery", label: "Local delivery", href: "/courier/local-delivery" },
  { group: "Local delivery", label: "Delivery partners", href: "/courier/local-delivery/partners" },
  { group: "Courier setup", label: "Providers", href: "/courier/providers" },
  { group: "COD", label: "COD remittances", href: "/courier/cod-remittances" },
];

export const sellerNav = [
  { label: "Dashboard", href: "/seller" },
  { label: "Store profile", href: "/seller/profile" },
  { label: "Onboarding", href: "/seller/register" },
  { label: "Products", href: "/seller/products" },
  { label: "Orders", href: "/seller/orders" },
  { label: "B2B Enquiries", href: "/seller/b2b-enquiries" },
  { label: "Reports", href: "/seller/reports/sales" },
  { label: "Subscription", href: "/seller/subscription" },
  { label: "Wallet", href: "/seller/finance/wallet" },
  { label: "Payouts", href: "/seller/finance/payouts" },
  { label: "Statements", href: "/seller/finance/statements" },
];
